### ISSUE TITLE
Set capture and camera view to current device with and height

### ISSUE THREAD

**Issue by hainakus** [VirtuoWorks/CanvasCameraPlugin#11]
I have tried without any result it just strech the canvas. Any help would be welcome.

**Comment by Sami-Radi** [comment]
Hello,

Could you give me more insight about your problem ? What options did you use to run the plugin ?

Best regards,

**Comment by hainakus** [comment]
Hi there Sami. situation is resolved using angular and cordova standalone. it was a css container problem.

I instaled bulma io framework and its working very well indeed.

I am using data to capture picture file from canvas and retrive color pixels from image.

regards

**Comment by hainakus** [comment]
Sorry false alarm it seems strange but it zooms the canvas video. do you know why?

**Comment by hainakus** [comment]
i am trying this but i think is messing around with camera canvas response....      

        window['plugin'].CanvasCamera.start(options, function(error) {

          console.log('[CanvasCamera start]', 'error', error);
        }, function(data) {
           console.log('[CanvasCamera start]', 'data', data);
          
           var canvas = _this.videoR.nativeElement;
           var context = canvas.getContext("2d");
           
            var imageObj = new Image();
            imageObj.onload = function(){
                context.drawImage(imageObj, 0, 0);
               
            };
            imageObj.src = data.output.images.fullsize.file;
          
            var imageData = context.getImageData(0,0, _this.width,
              _this.height)
            var data = imageData.data;
         
      
            })
          }

**Comment by Sami-Radi** [comment]
Hello,

The image is not zoomed. The image captured from the camera is always captured in landscape mode. This is the orientation of the camera cell. So the plugin rotates the image when in portrait mode before sending it to the js callback. Then the plugin js code has to resize center and crop the image to fit the avalaible space on the canvas in portrait mode. But if you override this part with a custom callback as you did you have the impression that the image is zoomed.

If your want to work on the displayed image you should use the onAfterDraw callback and access the frame.renderer.context property which contains the Canvas drawing context and avoid rewriting the Canvas projection code.

Best regards,

**Comment by hainakus** [comment]
great to hear~!!! thanks for the advice and knowledge. after all this is good plugin. great Sami.

best regards

**Comment by humblecoder** [comment]
Was this actually resolved?  It seems that you must hard-code dimensions rather than using something like `screen.width` to set the dimensions.  Currently I'm setting `640x480`, but I'm not sure how that's going to look on something like an `iPhone XR`.
