### ISSUE TITLE
Any suggestions on how to install this on a Meteor app?

### ISSUE THREAD

**Issue by SosaWISE** [VirtuoWorks/CanvasCameraPlugin#12]
I have a meteor app that I'm trying to capture Video and display it in a canvas tag that runs on iOS.  I can't figure out how to install this plugin.  

What I have done is to create the borilerplate meteor example and add the plugin.  Here are my steps in meteor:

$ meteor create --example angular2-boilerplate
$ meteor add-platform ios
$  meteor add cordova:com.virtuoworks.cordova-plugin-canvascamera@https://github.com/VirtuoWorks/CanvasCameraPlugin#b634fe23fb058ef3182cf0f37db13183937ad47f

Sow when I run the build command I get the following error:
=> Errors prevented startup:

   While installing Cordova plugins:
   error: Meteor no longer supports installing Cordova plugins from arbitrary tarball URLs. You can either add a plugin from a Git URL with a SHA reference, or from a
   local path. (Attempting to install from https://github.com/VirtuoWorks/CanvasCameraPlugin#b634fe23fb058ef3182cf0f37db13183937ad47f.)

=> Your application has errors. Waiting for file change.

**Comment by skifaster** [comment]
`meteor add cordova:com.virtuoworks.cordova-plugin-canvascamera@https://github.com/VirtuoWorks/CanvasCameraPlugin.git#b634fe23fb058ef3182cf0f37db13183937ad47f`
