### ISSUE TITLE
Mechanism for actual image capture?

### ISSUE THREAD

**Issue by humblecoder** [VirtuoWorks/CanvasCameraPlugin#14]
Is there a recommended mechanism for actual file capture, or must we simply "scrape" the canvas with a `toDataURL()`?  Attempting to use the `frame` object is proving unfruitful.  Since it's only available in a Cordova context, and I can't `JSON.stringify` it without error, I'm unable to verify what it contains or see how to use it.  Please advise.

**Comment by Sami-Radi** [comment]
Hello,

The `frame` object contains a `.image` property. This property contains the  HTMLImgElement which is drawn into the canvas. So if your set the initial CanvasCamera options object to `use: 'data',`, you can get the base64 image from the `frame.image.src` property. If you use the `use: 'file',` option, you can get the image base64 from the canvas itself with the `.toDataUrl()` method.

Best Regards,
