### ISSUE TITLE
Is there any example of the "onAfterDraw"?

### ISSUE THREAD

**Issue by fredchung1224** [VirtuoWorks/CanvasCameraPlugin#17]
I am not sure what data included with the "frame" in the "onAfterDraw" return.

Is there any example on that? Would like to get the image data, is there any image data included in the "frame"

Thank you

**Comment by Sami-Radi** [comment]
Hello,

You can access the image with `frame.image.src`. If you chose the data option, it should contain the base64, if you chose the file option, it should contain the file local URL.

I'll update the README.md file with the frame content description.

Best Regards,
