### ISSUE TITLE
installation on ionic 3

### ISSUE THREAD

**Issue by Avishaidev** [VirtuoWorks/CanvasCameraPlugin#19]
Plugin doesn't support this project's cordova-android version. cordova-android: 7.1.4, failed version requirement:
      <6.3.0

**Comment by Sami-Radi** [comment]
The current message : 

`Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement:
      <6.3.0
Skipping 'cordova-plugin-compat' for android`

Indicates that the **cordova-plugin-compat** dependency is not supported by your cordova version and therefore will not be installed. This plugin is required and installed if you are using an old cordova version (<6.3.0)

The **canvascamera** plugin is nevertheless **installed** and **supported** by your cordova version.

Best Regards,
