### ISSUE TITLE
save recording video as file?

### ISSUE THREAD

**Issue by Avishaidev** [VirtuoWorks/CanvasCameraPlugin#20]
any suggestion to save recording video as file?

**Comment by Sami-Radi** [comment]
The canvascamera plugin load each captured frame in the specified canvas tag in the webview. The frames can be loaded as individual image files or base64 data. 

A recording mode where the capture from the phone is saved as a video file and simultaneously streamed into the webview is not implemented by this plugin.

Best regards,
