### ISSUE TITLE
cameraPosition not set through options

### ISSUE THREAD

**Issue by petrot** [VirtuoWorks/CanvasCameraPlugin#22]
For me, the cameraPosition not set through the options object. Only works with window.plugin.CanvasCamera.cameraPosition('front');

**Comment by Sami-Radi** [comment]
Hello,

I've made a mistake in the documentation. Try

`
var options = {
    cameraFacing: 'front' // in the documentation i wrote cameraPosition: 'front' but it's cameraFacing: 'front'
};
window.plugin.CanvasCamera.start(options);
`
Best Regards,

**Comment by petrot** [comment]
@Sami-Radi thanks!
