### ISSUE TITLE
Typescript types not working

### ISSUE THREAD

**Issue by abdullahcel1k** [VirtuoWorks/CanvasCameraPlugin#27]
Hello i need run on ionic with angular but typescript types not working. 
`
> import * as CanvasCamera from 'cordova-plugin-canvascamera';
`
return this error : File '~/node_modules/@types/cordova-plugin-canvascamera/index.d.ts' is not a module.

**Comment by Sami-Radi** [comment]
The type definition has been made by a contributor [see here](https://github.com/VirtuoWorks/CanvasCameraPlugin/issues/8)
We are going to dig into this issue.

**Comment by Sami-Radi** [comment]
Hello, the latest plugin version entirely rewritten in typescript with its types. You can check a working typescript/angular demo [here](https://github.com/VirtuoWorks/canvascamera-capacitor-demo)
