### ISSUE TITLE
cant install 

### ISSUE THREAD

**Issue by warbadev** [VirtuoWorks/CanvasCameraPlugin#3]
while trying to use the demo i cant install the plugin through cordova command line
i get this error
Error: Failed to fetch plugin https://github.com/dekwilde/CanvasCameraPlugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
please if u can update to solve this issue
regards

**Comment by Sami-Radi** [comment]
Hello,

So the problem might be :

- You switched to a stalled old branch (Camera2) which is not maintained anymore. Stay on the master branch (I deleted the old branch just to be sure that this will not affect other testers). Besides our repo is https://github.com/VirtuoWorks/CanvasCameraPlugin.git and the repo https://github.com/dekwilde/CanvasCameraPlugin.git is nowhere to be found on the latest release so be sure that you are using the latest version of the plugin and demo.

- About the demo, when adding a platform, the plugin is automatically downloaded thanks to the Cordova config.xml file which states the plugin as a dependency. If the plugin is already installed, you can't install it again. I've updated the demo's README.md regarding this matter.

So please check it out, and tell me if the problem still occurs to you.

Best regards.
