### ISSUE TITLE
How to Record Video?

### ISSUE THREAD

**Issue by Saqib92** [VirtuoWorks/CanvasCameraPlugin#36]
Is there a way to Record Videos on both Android / IOS platform and get file URI to upload that video to server???

**Comment by Sami-Radi** [comment]
Hello, the plugin doesn't provide any means to record video. There are no plans to add this feature to the plugin.

**Comment by Saqib92** [comment]
> Hello, the plugin doesn't provide any means to record video. There are no plans to add this feature to the plugin.

Sorry, but what is the purpose of this plugin?

**Comment by Sami-Radi** [comment]
The plugin streams frames from captured from the mobile application native part into a canvas in the webview (html/css) part. 

You can access these frames and perform any operation you want with them using the JavaScript callbacks provided by the plugin.

So if you wish to, you can **add your own JS/TS logic** to :   
* Send each frames provided by the native part and drawn into the canvas to a server and reconstruct a video from the server-side using each frame provided by the plugin;
* Use tracking librairies on each frames into the canvas (using tracking js - **that's what we're using it for**) to detect objects or faces;
* Perfom drawings on each frames into the canvas for augmented reality for example;
* Or any other usage you see fit.

If you want to record videos, you should try other cordova plugins (for instance https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media-capture/index.html) or capacitor plugins (for instance https://github.com/TeamMaestro/capacitor-video-recorder)

We have no plans to add additional features into this plugin. However this is an open source project. So if you want to contribute and add additional features you can submit a pull request with the new feature or fork the project.

Best regards.
