### ISSUE TITLE
declares <uses-feature> for non-existing hardware feature; prevents listing on Google Play

### ISSUE THREAD

**Issue by Kevin-Hamilton** [VirtuoWorks/CanvasCameraPlugin#4]
Hello, 

Today I tried to release an app which uses this plugin and when uploading to the Google Play store, the app shows a "Supported Devices" list of ZERO.

Working with LiveChat support at Goolge Play store, they alerted me to an issue with the android.hardware.camera.setParameters feature.  Upon researching, I found that this plugin injects <uses-feature android:name="android.hardware.camera.setParameters" /> into my AndroidManifest.xml.

It appears there is no such Hardware feature, at least I don't see it listed on this reference page: https://developer.android.com/guide/topics/manifest/uses-feature-element.html#features-reference

By requiring a feature that no devices have, Google Play excludes the app from all devices.

The app will still sideload fine onto a test device over USB, which is why I did not catch this issue during testing.  The test device does not apparently care whether this manifest element exists, but Google Play store does.

**Comment by Sami-Radi** [comment]
Hello,

Indeed, I removed it from the plugin file. Its not a mandatory requirement.

Thanks for reporting the issue !
