### ISSUE TITLE
setCameraPosition is not a function

### ISSUE THREAD

**Issue by CovertIII** [VirtuoWorks/CanvasCameraPlugin#5]
The readme says to use setCameraPosition to change the direction the camera is facing.  However, it looks like the correct function to use would be cameraPosition.  There is no setCameraPosition function in www/CanvasCamera.js

See:
https://github.com/VirtuoWorks/CanvasCameraPlugin/blob/master/www/CanvasCamera.js#L416

Looks like the same would also apply to setFlashMode as well.

**Comment by Sami-Radi** [comment]
Thanks for reporting the issue.
