### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by lordazzi** [VirtuoWorks/CanvasCameraPlugin#8]
What about convert the JavaScript in project to TypeScript? For Angular 2 support?

**Comment by Sami-Radi** [comment]
Hello,

We plan on releasing a Ionic 3 test bench in the near future using the plugin and add a complete type definition file for it's TypeScript implementation.

For now, you can use the plugin within Ionic 3.0 but you will need to write your own type definition file.

Best regards,

**Comment by lordazzi** [comment]
Nice!

**Comment by lordazzi** [comment]
I have created the definition files for your lib and made the pull request for DefinitelyTyped.
You can see the pull request here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20061#event-1268200363

And you can download de definition files here:
https://www.npmjs.com/package/@types/cordova-plugin-canvascamera

**Comment by Sami-Radi** [comment]
Hello,

I've added some remarks about the type definition file on the related thread. I'll update our README.md with your type definition repository as soon as it is validated by the DefinitelyTyped team.

Thanks for your contribution. 👍 

Best Regards,

**Comment by lordazzi** [comment]
Nice, I'll work in that

**Comment by Sami-Radi** [comment]
Hello,

I've updated our README.md with your type definition repository.

Thanks for contributing.

Best Regards,
