### ISSUE TITLE
cordova-android: 7.0.0

### ISSUE THREAD

**Issue by Martin-Luckow** [VirtuoWorks/CanvasCameraPlugin#9]
Hi all.

In cordova-android: 7.0.0 it is not possible to install 'cordova-plugin-compat' anymore. Seems, that it is obsolete and its functions are covered by the new engine. Unfortunately, CanvasCameraPlugin depends on it, so it seems not to be possible to update apps to cordova-android: 7.0.0.

**Comment by Sami-Radi** [comment]
Hello, 

The latest plugin version is ignored when preparing the latest cordova-android app. I've upgraded the dependency with the latest plugin version. This should fix this issue while preserving compatibility with older cordova-android versions.

Thanks for reporting the issue.
